### ISSUE TITLE
Select element by Text

### ISSUE THREAD

**Issue by tomitrescak** [nodejs-enterprise/testisimo#1]
How can I select element by text? I do not think this is possible via CSS selectors.

**Comment by matusszabo** [comment]
Yes, it is not possible via CSS selectors, therefore there are some extra properties that will not be added to selector, but filtered after querySelectorAll:
1. isVisible - (empty or true / false) if element or one of its parents has display:none
2. innerText (alias textContent) - this will filter elements by inner text using https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
