### ISSUE TITLE
Reset page functionality

### ISSUE THREAD

**Issue by tomitrescak** [nodejs-enterprise/testisimo#3]
As you can see in the gif below, I need to manually refresh page every time I run the test as the click on the form element makes element disappear and in the second run the element is no longer displayed on the screen:

![testisimo](https://cloud.githubusercontent.com/assets/2682705/12081633/06cf2380-b2d3-11e5-8b67-91db85f02d61.gif)

I propose to have a "Load Page" or "Navigate TO" action that would start with navigating to a specific page.

**Comment by matusszabo** [comment]
Added "Location Reload" action with no arguments. If you want to set diferrent url, there is action "Location Set URL". Is this what you requested ?
